apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: git2consul
  name: git2consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git2consul
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: git2consul
    spec:
      containers:
      - image: shishirkhandelwal/git2consul:0.2
        name: git2consul
        command: ["/bin/sh","-c","sleep 40000"]
        resources: {}
        volumeMounts:
        - name: configuration
          mountPath: /tmp/configuration.json
          subPath: configuration.json
      volumes:
      - name: configuration
        configMap:
          name: configuration-file
status: {}
